# Site Settings
name: BlowByBlow
title: BlowByBlow | Blog by Keith
description: A simple life/hobby.
tags:
  - blog
  - jekyll
email: gtrfxdsp@gmail.com
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: gtrfx
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true

# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gtrfx.github.io" # the base hostname & protocol for your site
google_analytics: "UA-102853359-1"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title:output_ext
collections:
  authors: 
    output: true
paginate_path: "/page/:num/"
paginate: 10 

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-seo-tag

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed

include:
  - google49d1299e8b3f1acf.html